# Generated by Django 3.2.23 on 2023-11-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
