# Generated by Django 4.2.7 on 2023-11-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0002_product_description_alter_stock_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='stock_name',
        ),
    ]
