# Generated by Django 4.2.7 on 2023-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0002_salesbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='code_counter',
            field=models.IntegerField(default=0),
        ),
    ]
