# Generated by Django 4.2.7 on 2023-11-10 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0004_alter_product_status_alter_stock_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
