# Generated by Django 4.2.7 on 2023-11-12 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0005_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_per_order',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity_purchased',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity_sold',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
