# Generated by Django 4.2.7 on 2023-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0007_remove_stock_code_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(blank=True, default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
