# Generated by Django 3.2.23 on 2023-11-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0008_auto_20231116_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='product',
            new_name='product_name',
        ),
    ]
