# Generated by Django 3.2.23 on 2023-11-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0009_rename_product_salesitem_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stock_name',
        ),
    ]
