# Generated by Django 4.2.7 on 2023-11-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0010_alter_stock_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='code',
        ),
    ]
