# Generated by Django 3.2.23 on 2023-11-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0010_rename_name_stock_stock_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
