# Generated by Django 4.2.7 on 2023-11-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0011_remove_stock_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
