# Generated by Django 4.2.7 on 2023-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0012_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
