# Generated by Django 3.2.23 on 2023-11-17 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0012_auto_20231117_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='quantity_sold',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
