# Generated by Django 4.2.7 on 2023-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0013_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='billno',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
