# Generated by Django 3.2.23 on 2023-11-24 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0014_supplier_code_alter_salesbill_billno'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='amount_tendered',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
