# Generated by Django 4.2.7 on 2023-11-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0016_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_per_order',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
