# Generated by Django 4.2.7 on 2023-11-17 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0017_alter_product_qty_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_per_order',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
