# Generated by Django 4.2.7 on 2023-11-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0019_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
    ]
