# Generated by Django 4.2.7 on 2023-11-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0020_alter_stock_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_name',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='salesitem',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
