# Generated by Django 4.2.7 on 2023-11-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0021_rename_stock_name_product_stock_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='category',
        ),
    ]
