# Generated by Django 4.2.7 on 2023-11-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0022_rename_description_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='supplier',
            new_name='supplier_id',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='billno',
            new_name='purchaseBill_id',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='stock',
            new_name='stock_id',
        ),
    ]
