# Generated by Django 3.2.23 on 2023-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0023_rename_supplier_purchasebill_supplier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='billno',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
