# Generated by Django 4.2.7 on 2023-11-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0024_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
    ]
