# Generated by Django 3.2.23 on 2023-11-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0024_alter_salesbill_billno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='billno',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='billno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='inv_mgt.salesbill'),
        ),
    ]
