# Generated by Django 4.2.7 on 2023-11-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0025_remove_product_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
