# Generated by Django 3.2.23 on 2023-11-21 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0026_rename_quantity_sold_salesitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
