# Generated by Django 3.2.23 on 2023-11-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0027_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='menu',
        ),
    ]
