# Generated by Django 4.2.7 on 2023-11-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0028_rename_code_product_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='stock_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inv_mgt.stock'),
        ),
    ]
