# Generated by Django 4.2.7 on 2023-11-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0029_alter_purchaseitem_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchaseBill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_mgt.purchasebill'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='stock_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inv_mgt.stock'),
            preserve_default=False,
        ),
    ]
