# Generated by Django 4.2.7 on 2023-11-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0030_alter_purchaseitem_purchasebill_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='product_id',
            new_name='menu',
        ),
    ]
