# Generated by Django 4.2.7 on 2023-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0032_alter_salesbill_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
