# Generated by Django 4.2.7 on 2023-12-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0033_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
