# Generated by Django 4.2.7 on 2023-12-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0035_remove_purchaseitem_remarks_purchasebill_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_updated']},
        ),
    ]
