# Generated by Django 4.2.7 on 2023-12-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0036_alter_stock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='purchasebill',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AlterModelOptions(
            name='salesbill',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='salesitem',
            options={'ordering': ['-sale_date']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-date_updated']},
        ),
    ]
