# Generated by Django 4.2.7 on 2023-12-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0038_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
