# Generated by Django 4.2.7 on 2023-12-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0039_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='warning_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
