# Generated by Django 4.2.7 on 2023-12-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0041_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Owner',
        ),
    ]
