# Generated by Django 4.2.7 on 2023-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0042_rename_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='mode_of_payment',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
