# Generated by Django 4.2.7 on 2023-12-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0043_salesbill_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='show_notification',
            field=models.BooleanField(default=True),
        ),
    ]
