# Generated by Django 3.2.23 on 2023-12-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0045_auto_20231211_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
