# Generated by Django 4.2.7 on 2023-12-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0051_alter_salesitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
