# Generated by Django 4.2.7 on 2023-12-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0052_salesitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='inv_mgt.supplier'),
        ),
    ]
