# Generated by Django 4.2.7 on 2023-12-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_mgt', '0054_alter_product_menu_alter_product_stock_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_mgt.menu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_mgt.stock'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inv_mgt.stock'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='billno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='inv_mgt.salesbill'),
        ),
    ]
